name: robot_vision
channels:
  - conda-forge
  - defaults
dependencies:
  - aiodns=3.5.0=py313haa95532_1
  - aiohappyeyeballs=2.6.1=py313haa95532_0
  - aiohttp=3.12.15=py313h02ab6af_0
  - aiosignal=1.4.0=py313haa95532_0
  - ansi2html=1.9.2=py313haa95532_0
  - aom=3.9.1=he0c23c2_0
  - assimp=5.4.3=hf2fb9eb_0
  - attrs=25.4.0=py313haa95532_1
  - blinker=1.9.0=py313haa95532_0
  - blosc=1.21.6=h4190f5b_0
  - brotli-python=1.0.9=py313h5da7b33_9
  - brotlicffi=1.0.9.2=py313h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.5=h731ff69_0
  - ca-certificates=2025.9.9=haa95532_0
  - cairo=1.18.4=h5782bbf_0
  - certifi=2025.10.5=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - charset-normalizer=3.4.4=py313haa95532_0
  - click=8.2.1=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - dash=2.14.2=py313haa95532_0
  - dav1d=1.2.1=h2bbff1b_0
  - double-conversion=3.3.1=h5da7b33_0
  - eigen=3.4.0=h59b6b97_0
  - embree=4.3.3=ha827246_0
  - expat=2.7.1=h8ddb27b_0
  - ffmpeg=7.1.0=gpl_h2585aa8_705
  - flask=3.0.3=py313haa95532_0
  - flask-compress=1.17=py313haa95532_0
  - fmt=11.0.2=hf4da5c8_1
  - font-ttf-dejavu-sans-mono=2.37=hd3eb1b0_0
  - font-ttf-inconsolata=2.001=hcb22688_0
  - font-ttf-source-code-pro=2.030=hd3eb1b0_0
  - font-ttf-ubuntu=0.83=h8b1ccd4_0
  - fontconfig=2.15.0=hd211d86_0
  - fonts-anaconda=1=h8fa9717_0
  - fonts-conda-ecosystem=1=hd3eb1b0_0
  - freetype=2.13.3=h0620614_0
  - fribidi=1.0.10=h62dcd97_0
  - frozenlist=1.8.0=py313h885b0b7_0
  - gdk-pixbuf=2.42.12=hed59a49_0
  - gl2ps=1.4.2=hce2df77_1
  - glew=2.1.0=hd77b12b_3
  - glfw=3.4=h02ab6af_0
  - graphite2=1.3.14=hd77b12b_1
  - harfbuzz=11.0.0=h9e37d49_0
  - hdf4=4.2.15=h5557f11_7
  - hdf5=1.14.4=nompi_hd5d9e70_105
  - icu=75.1=he0c23c2_0
  - idna=3.11=py313haa95532_0
  - importlib-metadata=8.5.0=py313haa95532_0
  - itsdangerous=2.2.0=py313haa95532_0
  - jinja2=3.1.6=py313haa95532_0
  - jsoncpp=1.9.6=hdc05c43_0
  - krb5=1.21.3=h885b0b7_4
  - lerc=4.0.0=h5da7b33_0
  - libaec=1.1.3=hcdb6601_0
  - libblas=3.9.0=35_h5709861_mkl
  - libcblas=3.9.0=35_h2a3cdd5_mkl
  - libclang13=20.1.8=default_hccbf073_0
  - libcurl=8.16.0=h97e0424_0
  - libdeflate=1.22=h2466b09_0
  - libexpat=2.7.1=hac47afa_0
  - libffi=3.4.4=hd77b12b_1
  - libglib=2.84.0=h7025463_0
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.18=hc1393d2_2
  - libintl=0.22.5=h5728263_3
  - libjpeg-turbo=3.1.1=h02ab6af_0
  - libkrb5=1.21.3=h885b0b7_4
  - liblapack=3.9.0=35_hf9ab0e9_mkl
  - liblapacke=3.9.0=35_h3ae206f_mkl
  - libllvm20=20.1.8=h3aa9ab2_0
  - liblzf=3.6=h2466b09_3
  - libmpdec=4.0.0=h827c3e9_0
  - libnetcdf=4.9.2=nompi_h5bdc103_116
  - libogg=1.3.5=h2bbff1b_1
  - libopus=1.5.2=h2466b09_0
  - libpng=1.6.50=h46444df_0
  - librsvg=2.58.4=h5ce5fed_3
  - libsodium=1.0.20=h83e8143_0
  - libsqlite=3.50.4=hf5d6505_0
  - libssh2=1.11.1=h2addb87_0
  - libtheora=1.1.1=h8cc25b3_3
  - libtiff=4.7.0=hfc51747_1
  - libuv=1.48.0=h827c3e9_0
  - libwebp-base=1.6.0=h4d5522a_0
  - libxml2=2.13.9=h6201b9f_0
  - libzip=1.11.2=h3135430_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=20.1.8=h29ce207_0
  - loguru=0.7.2=py313haa95532_1
  - lz4-c=1.9.4=h2bbff1b_1
  - markupsafe=3.0.2=py313h827c3e9_0
  - minizip=4.0.3=hb68bac4_0
  - mkl=2024.2.2=h57928b3_16
  - msgpack-python=1.1.1=py313h5da7b33_0
  - multidict=6.7.0=py313h02ab6af_0
  - narwhals=2.7.0=py313haa95532_0
  - nest-asyncio=1.6.0=py313haa95532_0
  - nlohmann_json=3.11.2=h6c2663c_0
  - open3d=0.18.0=py313h53eab1a_14
  - openh264=2.5.0=ha9db3cd_0
  - openssl=3.5.4=h725018a_0
  - packaging=25.0=py313haa95532_1
  - pango=1.56.3=h0c53d3b_1
  - pcre2=10.44=h99c9b8b_2
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h4043f72_0
  - plotly=6.3.0=py313h4442805_0
  - proj=9.5.1=h4f671f6_0
  - propcache=0.3.1=py313h827c3e9_0
  - pugixml=1.14=h63175ca_0
  - pycares=4.10.0=py313he29e43d_0
  - pycparser=2.23=py313haa95532_0
  - pysocks=1.7.1=py313haa95532_1
  - python=3.13.9=h260b955_100_cp313
  - python_abi=3.13=1_cp313
  - qhull=2020.2=h59b6b97_2
  - qt6-main=6.8.3=h72a539a_1
  - requests=2.32.5=py313haa95532_0
  - retrying=1.3.3=pyhd3eb1b0_2
  - setuptools=80.9.0=py313haa95532_0
  - six=1.17.0=py313haa95532_0
  - sqlite=3.50.2=hda9a48d_1
  - svt-av1=2.3.0=he0c23c2_0
  - tbb=2021.13.0=h18a62a1_3
  - tbb-devel=2021.13.0=h4eb897c_3
  - tinyobjloader=1.0.7=h63175ca_2
  - tk=8.6.15=hf199647_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - utfcpp=3.2.1=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - vtk-base=9.3.1=qt_py313hdcf24be_209
  - werkzeug=3.0.6=py313haa95532_0
  - wheel=0.45.1=py313haa95532_0
  - win32_setctime=1.1.0=pyhd3eb1b0_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - winloop=0.3.1=py313h913537a_0
  - wslink=2.5.0=pyhd8ed1ab_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.6.4=h4754444_1
  - yarl=1.18.0=py313h827c3e9_0
  - zeromq=4.3.5=h6c54ac7_1
  - zipp=3.21.0=py313haa95532_0
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.24.0=py313he335c29_0
  - zstd=1.5.7=h56299aa_0
  - pip:
      - genicam==1.5.0
      - harvesters==1.4.3
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - pymodbus==3.11.3
      - pypylon==4.2.0
prefix: C:\Users\User\anaconda3\envs\robot_vision
